app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template
from . import home
from ..models import *


@home.route('/')
def home_page():
    """
    Home Handler
    """
    projects = Project.query.all()
    return render_template('home/index.html', projects=projects)


@home.route('/q')
def q_test():
    """
    Quickie Handler
    q.cgi convert
    """
    return render_template('home/quickie.html')

app/templates/home/admin.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>For administrators only!</h3>
                    <hr class="intro-divider">
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block head_js%}
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-11144858-1']);
    _gaq.push(['_setDomainName', '.ilpga.fr']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    
  var BrowserDetect = {
      init: function () {
          this.browser = this.searchString(this.dataBrowser) || "An unknown browser";
          this.version = this.searchVersion(navigator.userAgent)
              || this.searchVersion(navigator.appVersion)
              || "an unknown version";
          this.OS = this.searchString(this.dataOS) || "an unknown OS";
      },
      searchString: function (data) {
          for (var i=0;i<data.length;i++)	{
              var dataString = data[i].string;
              var dataProp = data[i].prop;
              this.versionSearchString = data[i].versionSearch || data[i].identity;
              if (dataString) {
                  if (dataString.indexOf(data[i].subString) != -1)
                      return data[i].identity;
              }
              else if (dataProp)
                  return data[i].identity;
          }
      },
      searchVersion: function (dataString) {
          var index = dataString.indexOf(this.versionSearchString);
          if (index == -1) return;
          return parseFloat(dataString.substring(index+this.versionSearchString.length+1));
      },
      dataBrowser: [
          {
              string: navigator.userAgent,
              subString: "Chrome",
              identity: "Chrome"
          },
          { 	string: navigator.userAgent,
              subString: "OmniWeb",
              versionSearch: "OmniWeb/",
              identity: "OmniWeb"
          },
          {
              string: navigator.vendor,
              subString: "Apple",
              identity: "Safari",
              versionSearch: "Version"
          },
          {
              prop: window.opera,
              identity: "Opera",
              versionSearch: "Version"
          },
          {
              string: navigator.vendor,
              subString: "iCab",
              identity: "iCab"
          },
          {
              string: navigator.vendor,
              subString: "KDE",
              identity: "Konqueror"
          },
          {
              string: navigator.userAgent,
              subString: "Firefox",
              identity: "Firefox"
          },
          {
              string: navigator.vendor,
              subString: "Camino",
              identity: "Camino"
          },
          {		// for newer Netscapes (6+)
              string: navigator.userAgent,
              subString: "Netscape",
              identity: "Netscape"
          },
          {
              string: navigator.userAgent,
              subString: "MSIE",
              identity: "Explorer",
              versionSearch: "MSIE"
          },
          {
              string: navigator.userAgent,
              subString: "Gecko",
              identity: "Mozilla",
              versionSearch: "rv"
          },
          { 		// for older Netscapes (4-)
              string: navigator.userAgent,
              subString: "Mozilla",
              identity: "Netscape",
              versionSearch: "Mozilla"
          }
      ],
      dataOS : [
          {
              string: navigator.platform,
              subString: "Win",
              identity: "Windows"
          },
          {
              string: navigator.platform,
              subString: "Mac",
              identity: "Mac"
          },
          {
                 string: navigator.userAgent,
                 subString: "iPhone",
                 identity: "iPhone/iPod"
          },
          {
              string: navigator.platform,
              subString: "Linux",
              identity: "Linux"
          }
      ]
  
  };
  BrowserDetect.init();  
</script>
{% endblock %}
{% block body %}
    <div class="arbortitle fg-toolbar ui-widget-header ui-helper-clearfix">
        <a href='.' style='position: absolute;left:0px;'><img src="{{ url_for ('static', filename='images/arboratorNano.png') }}" border="0"></a>
        <span style='text-align:center;margin:0 auto;position: relative;top:0px;' id='sentinfo'>Welcome to the Arborator website!</span>
    </div>
    <!--Project listing and stuff-->
    <div style="text-align:center">
            <div><a href="{{ url_for('home.q_test') }}"><p>Test run Arborator</p></a></div>
            {% if projects %}
                {% for project in projects %}
                    <a href = "{{ url_for('project.projectpage', project_name=project.name)}}">{{ project.name }}</a>
                {% endfor %}
            {% else %}
                No projects have been created
            {% endif %}
    </div>
    
    <!--info box-->
    <div class='ui-widget ui-widget-content ui-corner-all' style='padding: 2em; margin-left: 199px; margin-right: 199px;clear: both;text-align:center;position: relative;'>
            <p style="font-size:.7em;margin:1;">
                <img border="0" src="{{ url_for ('static', filename='images/arboratorNano.png') }}" align='middle'>
        Arborator is free software.
            </p><br><hr>
            <table style='margin-top:0;width:100%'><tr><td>
            <p style="font-size:.7em;margin:1;">
            <a href="http://www.gnu.org/licenses/agpl-3.0.html">
        It is realeased under the 
            </p> <p style="font-size:.7em;margin:1;">
            
                <img src="{{ url_for ('static', filename='images/Affero_General_Public_License_3.png') }}" align='middle'>
        licence
            </td>
            
            </tr>
            </table></a></p> <p style="font-size:.7em;margin:1;">   
        It can <a href="http://rhapsodie.ilpga.fr/wiki/Arborator#site_administration_and_installation">easily be installed on any Apache server.</a>
            </p><p style="font-size:.7em;margin:1;">
        This software relies on your browser's SVG capacity and is written principally for use in the 
            <img border="0" src="{{ url_for ('static', filename='images/firefox.grey.png') }}" align='middle'> 
        Firefox browser.
            <br><br>
            <script>
                if (BrowserDetect.browser=="Firefox") document.write("You are using Firefox "+BrowserDetect.version+" on "+BrowserDetect.OS+". Everything should work fine.");
                else if (BrowserDetect.browser=="Chrome") document.write("You are using Chrome "+BrowserDetect.version+" on "+BrowserDetect.OS+". This Browser is not fully tested.");
                else document.write("You are using an unsupported browser ("+BrowserDetect.browser+" "+BrowserDetect.version+" on "+BrowserDetect.OS+"). Arborator is fully functional only on Firefox.");
            </script>
        </p>
        <br>
        <div class="ui-widget ui-widget-content ui-corner-all"  style='
        font:italic normal .8em/1em Times, serif;text-align:center;margin:0 auto;padding:1em;'>
            written by <a href='http://gerdes.fr'>Kim Gerdes</a><br/><br/>
            <a href='http://www.univ-paris3.fr/'>Sorbonne nouvelle</a>,
            <a href='http://ilpga.fr/'>ILPGA</a>,
            <a href='http://lpp.univ-paris3.fr/'>LPP</a>
            (<a href='http://lpp.univ-paris3.fr/'>CNRS</a>)
            
            <br><br>
            
            <a href="https://github.com/kimgerdes/arborator"><img style="position: absolute; top: 0; right: 0; border: 0;" src="{{ url_for ('static', filename='images/forkme.png') }}" alt="Fork me on GitHub"></a>
        
        </div>
    </div>
        
{% endblock %}

app/templates/home/quickie.html
{% extends "base.html" %}
{% block title %}Quickie{% endblock %}
{% block head_js%}
<script type='text/javascript' > 
    var currentsvg = "mmmm"; 
</script>
<script type="text/javascript" src="{{ url_for('static', filename='js/arborator.draw.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/q.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/jsundoable.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/colpick.js') }}"></script>

<link href="{{ url_for('static', filename='css/arborator.css') }}" rel="stylesheet" type="text/css">
<link href="{{ url_for('static', filename='css/colpick.css') }}" rel="stylesheet" type="text/css">


<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/jquery.svg.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/jquery.svgdom.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/jquery.timeago.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/waypoints.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/jquery.address.min.js') }}"></script>

<!--brat helper modules-->
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/configuration.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/util.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/annotation_log.js') }}"></script>

<!--<script type="text/javascript" src="annodoc/webfont.js"></script>-->
<!--brat modules-->
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/dispatcher.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/url_monitor.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/visualizer.js') }}"></script>

// embedding configuration
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/config.js') }}"></script>
// project-specific collection data
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/collections.js') }}"></script>

// NOTE: non-local libraries
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/annodoc.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/annodoc/conllu.js') }}"></script>
        
<link rel="stylesheet" href="{{ url_for('static', filename='js/annodoc/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='js/annodoc/style.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='js/annodoc/style-vis.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='js/annodoc/hint.css') }}"/>
{% endblock %}
{% block body %}
        <div id="navigation" style="width:100%;margin:0px;border:0px;" class="arbortitle  ui-widget-header ui-helper-clearfix">
            <a href='.' style='position: fixed;left:1px;top:1px'><img src="{{ url_for('static', filename='images/arboratorNano.png') }}" border="0" title="Arborator Main Page"></a>
            <img src="{{ url_for('static', filename='images/q.png') }}" border="0" title="Arborator – Quickedit">
            <a style="position: fixed;right:1px;top:1px;right:5px;" id='help' title="restart the help animation"><img src="{{ url_for('static', filename='images/help.png') }}" style="vertical-align: text-top" border="0">Help</a>
        </div>
        <div id="center" class="center" style="width:100%;float:right;top:0px;">
            <div id="trees">
        </div>
        <form method="post" action="convert_svg.cgi?project=quickie" name="ex" id="ex" style=" position:fixed;top:6px;right:30px;display:none;"  target="_blank">
                <input type="hidden" id="source" name="source" value="">
                <select id="exptype" name="type" class="ui-button ui-state-default ui-corner-all" style="height:16px;font: italic 10px Times,Serif;border:thin solid silver;" >
                    <option>pdf</option>
                    <option>ps</option>
                    <option>odg</option>
                    <option>jpg</option>
                    <option>png</option>
                    <option value="tif">tiff</option>
                    <option>svg</option>
                </select>
                <input type="button" title="export" value="export" class="ui-button ui-state-default ui-corner-all" onClick="exportTree();"  style="padding: 0.0em 0.0em;" >
            </form>
            <div id="toggleAndBoxx" class="toggleAndBoxx">
                <div id="toggle" class="toggle" title="click here to show and hide the CoNLL input"></div>
                <div id="boxx" class="boxx">
                    <div class="arrow" title="you can click here (or anywhere else outside the box) when you have finished editing the CoNLL format or sentence text area">⬌</div>
                    <div id="textual" class="textual">Paste and edit CoNLL file below:
                        <TEXTAREA NAME="conll" id="conll" title="Here you can paste and edit CoNLL files with 4, 10 or 14 columns" style="width:100%; height:400; background-image: url('static/images/conll10.png'); background-repeat: no-repeat; background-position: 95% bottom; "># conllu format
                            1	faut	falloir	V	_	_	0	root	_	must
                            2	que	que	C	_	_	4	mark	_	that
                            3	tu	tu	Pron	_	_	4	nsubj	_	you
                            4	fasses	faire	V	_	_	1	ccomp	_	make
                            5	envie	envie	N	_	_	4	dobj	_	desire
                            6-7	aux	aux	P+D	_	_	_	_	_	to_the
                            6	à	à	P	_	_	8	case	_	to
                            7	les	le	D	_	_	8	det	_	the
                            8	enfants	enfant	N	_	_	4	iobj	5:nmod	kids
                            9	de	de	P	_	_	10	mark	_	to
                            10	faire	faire	V	_	_	5	ccomp	_	make
                            11-12	du	du	P+D	_	_	_	_	_	of_the
                            11	de	de	P	_	_	13	case	_	of
                            12	le	le	D	_	_	13	det	_	the
                            13	bruit	bruit	N	_	_	10	dobj	_	noise
                            
                            # conllu format using SpaceAfter=No
                            1	Can	can	AUX	MD	VerbForm=Fin	3	aux	_	_
                            2	you	you	PRON	PRP	Case=Nom|Person=2|PronType=Prs	3	nsubj	_	_
                            3	use	use	VERB	VB	VerbForm=Inf	0	root	_	_
                            4	the	the	DET	DT	Definite=Def|PronType=Art	10	det	_	_
                            5	'	'	PUNCT	``	_	6	punct	_	SpaceAfter=No
                            6	find	find	VERB	VB	VerbForm=Inf	10	compound	_	_
                            7	my	my	PRON	PRP$	Number=Sing|Person=1|Poss=Yes|PronType=Prs	8	nmod:poss	_	_
                            8	phone	phone	NOUN	NN	Number=Sing	6	dobj	_	SpaceAfter=No
                            9	'	'	PUNCT	''	_	6	punct	_	_
                            10	feature	feature	NOUN	NN	Number=Sing	3	dobj	_	_
                            11	to	to	PART	TO	_	12	mark	_	_
                            12	track	track	VERB	VB	VerbForm=Inf	3	advcl	_	_
                            13	someone	someone	NOUN	NN	Number=Sing	16	nmod:poss	_	_
                            14	else	else	ADJ	JJ	Degree=Pos	13	amod	_	SpaceAfter=No
                            15	's	's	PART	POS	_	13	case	_	_
                            16	phone	phone	NOUN	NN	Number=Sing	12	dobj	_	SpaceAfter=No
                            17	?	?	PUNCT	.	_	3	punct	_	_
                            
                            # I wrote the letter with a quill.
                            1	Я	ja	PRON	_	Case=Nom|Number=Sing|Person=1|PronType=Prs	2	nsubj	_	I
                            2	написал	napisat'	VERB	_	Gender=Masc|Number=Sing|VerbForm=Part|Voice=Act	0	root	_	wrote
                            3	письмо	pis'mo	NOUN	_	Case=Acc|Gender=Neut|Number=Sing	2	dobj	_	the-letter
                            4	пером	pero	NOUN	_	Case=Ins|Gender=Neut|Number=Sing	2	nmod	_	with-a-quill</TEXTAREA>          
                                <div style='float:xxx;'>
                                    <div><span style='float:left;'>additional functions</span> <input type='text' id='addfuncs'  style='width:100%' title='Here you can add additional functions that do not appear in the CoNLL data (space or comma separated) in order to make them appear in the drop down menu when editing.' value='nsubj csubj nsubjpass csubjpass dobj ccomp xcomp iobj vocative aux mark discourse auxpass expl cop neg root advmod dislocated nmod advcl nummod acl amod appos det nmod case compound mwe goeswith name foreign list parataxis remnant reparandum conj cc punct dep'></input></div>
                                    <div><span style='float:left;'>additional POS tags</span> <input type='text' id='addcats'  style='width:100%;' title='Here you can add additional categories that do not appear in the CoNLL data (space or comma separated) in order to make them appear in the drop down menu when editing.' value='ADJ ADP PUNCT ADV AUX SYM INTJ CONJ X NOUN DET PROPN NUM VERB PART PRON SCONJ _'>  </input> </div>

                                    <div>or paste your sentences here:
                                        <TEXTAREA NAME="sentences" id="sentences"  title='Here you can provide unanalyzed textual data, one sentence per line. You can then interactively add the syntactic analysis of your sentences. This will erase all the existing trees'  style="width:100%; height:100;"></TEXTAREA>
                                    </div>
                                    <input type="checkbox" id="annodoccheck"><label for="annodoccheck"><img src="{{ url_for('static', filename='images/annodoc.png') }}" border='0' title='show annodoc graph' style='top:0px;'>  </label>
                                    <div style='float:right;'>
                                        <img  id="style" src="{{ url_for('static', filename='images/style.png') }}" border='0' title='style' style='top:0px;'>   
                                    </div>
                                    <div id="styledialog" title="Design your dependency tree" style="background-color: white;">
                                        <div id="stylefunctions" title="functions"></div>
                                        <div style='float:right;'>
                                            <input type="checkbox" id="styleconllcheck">include style information in CoNLL
                                        </div>
                                    </div>
                                    <br>
                    </div>
                </div>
            </div> 
            <div id="funcform" style="display:none;position:absolute;">
                    <form  method="post" id="func" name="func" >
                        <select id="funchoice" class='funcmenu' onClick="changeFunc(event);" size=0 style="height:0; width:80px;"  >
                        </select>
                    </form>
            </div>
            <div id="catform" style="display:none;position:absolute;">
                <form  method="post" id="cat" name="cat" >
                    <select id="catchoice" class='funcmenu' onClick="changeCat();"  size=0 style="height:0; width:80px;"  >
                    </select>
                </form>
            </div>
            <div id="dialog" title="Confirmation" style="display: none;" >
                <div class="ui-state-error ui-corner-all" style="margin: 40px;padding: 10pt 0.7em;">
                    <h2 id="question">Are you sure?</h2>
                </div>
            </div>
            <div id="b" class="rbubble" style="right: 650px;top: 44px; position: absolute;display:none;">Paste a CoNLL file content here</div>
            <div id="bb" class="rbubble" style="right: 650px;top: 533px;position: absolute;">Or paste the sentences you want to analyze here.<br/>One sentence per line.</div>
            <div id="bbb" class="lbubble" style="left: 400px;top: 400px;position: absolute;">As soon as you click anywhere else, the graph is updated and you can modify the dependencies by dragging one word over the other.</div>
            <div id="bbbb" class="lbubble" style="left: 400px;top: 35px;position: absolute;">You can export the graph in various formats by clicking on the green arrow.</div>
            <input type="button" id="drawbutton" value="draw" class="ui-button ui-state-default ui-corner-all" onClick='$("#funchoice").empty(); $("#catchoice").empty();$("#stylefunctions").empty();$("#trees").empty();readConll();setupStyleDialog();drawTrees();nokeys=false;'  style="display: none;" >
{% endblock %}