app/project/__init__.py
from flask import Blueprint

project = Blueprint('project', __name__)

from . import views

app/project/views.py
from flask import render_template
from flask_login import login_required
from app import requires_access_level
from . import project
from ..models import *


def check_admin():
    """
    Prevent non-admins from accessing the page
    """
    if not current_user.is_admin:
        abort(403)

###################################### Admin Dashboard Views and Functions ######################################
@project.route('/<project_name>/admin')
@login_required
@requires_access_level(2)
def admin_dash(project_name): 
	"""
	Project Dashboard Handler
	"""
	check_admin()
	project = Project.query.filter_by(name=project_name).first()
	users = User.query.all()
    return render_template('project/dashboard.html', project=project, users=users)


@project.route('/<project_name>/admin/add/<int:id>', methods=['GET', 'POST'])
@login_required
@requires_access_level(2)
def add_user(id, project_id):
    check_admin()
	user = User.query.get_or_404(id)
	user.project_id = project_id
	db.session.add(user)
	db.session.commit()
	flash('You have successfully added a user to your project.')
    return render_template('projects/add_user.html')## testing include function 
	##angular style of template inclusion and value inheritance



@project.route('/<project_name>/admin/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@requires_access_level(2)
def edit_role(id, role):
    check_admin()
	user = User.query.get_or_404(id)
	user.role = role
	db.session.add(user)
	db.session.commit()
	flash('You have successfully changed a users role')
    return render_template('projects/dashboard.html')


@project.route('/<project_name>/admin/remove/<int:id>', methods=['GET', 'POST'])
@login_required
@requires_access_level(2)
def remove_user(id):
    user = User.query.get_or_404(id)
	db.session.delete(user.project_id)
	db.session.commit()
    flash('You have successfully removed a user.')
    return render_template('projects/dashboard.html', )


###################################### Project Page Views and Functions ######################################
@project.route('/<project_name>')
def projectpage(project_name):
    """
    Project Page Handler
    """    
    ##check if user assigned
    ##read in user congig files
    ##associate user with particular project

    return render_template('projects/index.html',project_name=project_name, title=project_name)




######################ignore for now####################################################################
###################33db operations###############################33
def export(textname, exportNumber, exportType, project):
    	#textname=textname.encode("utf-8")
	print "<h2>Exporting",textname.encode("utf-8"),"(text number",exportNumber,")</h2>"
	
	if textname:
		fc,users,sc,doublegovs=sql.exportAnnotations(int(exportNumber), textname, exportType )
		if fc==0: 	print "<div style='padding:10;' class='ui-state-error ui-corner-all'>No files were exported, probably because the file is assigned to nobody.</div><br/>"
		else:		
			print "Exported",fc,"files and a total of",sc,"sentences.<br/><br/>"
			if exportType in ["allconll","allxml"]:
				print "Exported all existing annotated trees into",
				if exportType =="allconll": print textname.encode("utf-8")+".user.trees.conll files.<br/>"
				else: print textname.encode("utf-8")+".user.trees.rhaps.xml files.<br/>"
			else: 
				print "Exported complete files for each assignment into"
				if exportType =="todoconll": print textname.encode("utf-8")+".user.complete.conll10 files.<br/>"
				else: print textname.encode("utf-8")+".user.complete.rhaps.xml files.<br/>"
		print "<br/><div style='padding:10;'  class='ui-state-highlight ui-corner-all'>",
		if fc==1:print "The export file for",users[0],"is"
		else: print "All the",fc,"export files (for",(", ".join(users)).encode("utf-8")+") are"
		print " in the export folder <strong style='color:#DD137B'><a href='projects/{project}/export' target='_blank'>inside the project folder</a></strong> on the server.</div><br/>".format(project=project.replace("'","\\'").replace('"','\\"').encode("utf-8"))
		if doublegovs: print "<div style='padding:10;' class='ui-state-error ui-corner-all'>Achtung!<br/> The annotation contains multiple governors for one or more nodes. The lines have been doubled, and thus this is not a common Conll format!</div>"
	else:
		print "problem: no textname"


def reaction(project,projectconfig,sql,userid,form,query):
    	"""
	contains reaction to actions, eg. uploading, erasing, exporting, ...
	"""
	filename = form.getvalue("filename",None)
	if filename: # upload file	
		from lib.treebankfiles import uploadConll
		filetype = form.getvalue("filetype",None)
		print "trying to upload",filename,filetype,"into the database of the project",project.encode("utf-8")
		if filetype in ["conll4","conll10","conll14"]:
			print "---------- here we go"
			nrsentences = uploadConll(sql,filename)
			print """<div class="ui-widget ui-widget-content ui-corner-all box">I added {nrsentences} sentences from {filename}.</div>""".format(nrsentences=nrsentences,filename=filename)
		else:	print """<div class="ui-widget ui-widget-content ui-corner-all box">Strange filetype: {filename}.</div>""".format(filename=filename)

	eraseNumber = form.getvalue("eraseNumber",None)
	if eraseNumber: # erase text
		print "erasing text number ",eraseNumber,"<br/>"
		sc=sql.removeText(int(eraseNumber))
		print "erased",sc,"sentences."

	#statustextid = form.getvalue("statustextid",None)
	#if statustextid: # erase text
		##print "statustextid, text number:",statustextid,"<br/>"
		#sql.statustext(int(statustextid),userid)

	exportNumber = form.getvalue("exportNumber",None)
	textname=None
	if exportNumber: # export text
		print '<div class="ui-widget ui-widget-content ui-corner-all box" >'
		
		textname = form.getvalue("textname",None)
		exportType = form.getvalue("exportType",None)
		#print exportNumber,type(exportNumber)
		exportNumber=int(exportNumber)
		if exportNumber==-1 :
			for t,tid in sorted( [(t,tid) for tid,t,nrtokens in sql.getall(None, "texts", None, None)]):
				export(t, tid, exportType, project)
			
		else: export(textname, exportNumber, exportType, project)
		
		print '</div>'

		
	userchoice = form.getlist('userchoice')
	textid = form.getvalue("textid",None)

	if userchoice and textid: # change todos
		removeid = int(form.getvalue("removeid",0))
		validator = int(form.getvalue("validator",0))
		if removeid:
			sql.removetextfromuser(int(textid),removeid)
		else:
			u=userchoice[0].split("(")[-1][:-1]
			sql.addtext2user(textid,u,validator)
			
	
	exochoice = form.getvalue("exochoice",None)
	if exochoice:
		
		textid = form.getvalue("textid",None)
		exotoknum = form.getvalue("exotoknum",None)
		
		print "changing exostatus of text id",textid,"to",exochoice
		sql.setExo(textid, exochoice, exotoknum)
		
	
	if query: # search results	
		print """<div class="ui-widget ui-widget-content ui-corner-all box"  style="text-align:-moz-center;">"""
		
		res = sql.snippetSearch(query)
		if res: 
			print "<h2>Search results for {query}:</h2>".format(query=query)
			print res.encode("utf-8")
		else: print "no results for {query}</h2>".format(query=query)
		print """</div>"""

app/templates/projects/add_user.html
<!-- {% extends "base.html" %}
{% block title %}
    Add User
{% endblock %}
{% block body %} -->
<table class="table table-striped table-bordered">
        <thead>
            <tr>
            <th width="45%"> Name </th>
            <th width="15%"> Add </th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.name }}</td>
                <td><a href="{{ url_for('project.add_user', id=user.id,) }}">
                        <i class="fa fa-pencil"></i> Add </a></td>
            </tr>
        </tbody>
    </table>    
{% endblock %}

app/templates/projects/dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>For {{ project.name }} administrators only!</h3>
                    <hr class="intro-divider">
                    There are currently {{project.users.count()}} users working on this project.
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                            <th width="15%"> Name </th>
                            <th width="15%"> Role </th>
                            <th width="15%"> Edit </th>
                            <th width="15%"> Remove </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in project.users %}
                            <tr>
                                <td>{{ user.name }}</td>
                                <td><input type = "text" name = "role" value="{{ user.role }}" /></td>
                                <td><a href="{{ url_for('project.edit_role', id=user.id, role=role ) }}">
                                    <i class="fa fa-pencil"></i> Edit </a></td>
                                <td><a href="{{ url_for('project.remove_user', id=user.id) }}">
                                        <i class="fa fa-trash"></i> Remove </a></td>
                            </tr>
                        </tbody>
                    </table>
                    Add New Users<!--onClick show buttons-->
                    {% include "add_user.html" %}
                    Upload Files
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/projects/index.html
{% extends "base.html" %}
{% block title %}{{project}}{% endblock %}
{% block head_js %}
<script type="text/javascript">	
	project="{project}";
	userid="{userid}";
	username="{username}";
    $('html').click(function() {
		$("#exportdiv").css({ display: 'none' } );	
		$("#userform").css({ display: 'none' } );	
		$("#exoform").css({ display: 'none' } );	
		});

	edit = function(textid,opensentence) {
		$("#textid").attr("value", textid );
		$("#opensentence").attr("value", opensentence );
		$("#editorform").submit();
	    }
	removeSample = function(textid, text) {
		$("#eraseNumber").attr("value",textid);
		$("#question").html("Are you sure that you want to erase the text "+text+" from the database?")
		$('#dialog').dialog('open');
		}
	exportAnnos = function(textid, text, offset) {
		$("#exportNumber").attr("value",textid);
		$("#textname").attr("value",text);
		offset.left=offset.left-280;
		$("#exportdiv").offset(offset).css({ display: 'inline' } );
		}	
	exportGo = function(type) {
		$("#exportType").attr("value",type);
		console.log($("#export"))
		$("#export").submit();
		$("#dialog").html("<img src='images/loading.gif'>");
		$("#dialog").dialog({
			height: 230,
 			width:150,
			modal: true,
			title:"Please wait!!!<br>This can be long.",
			buttons: {}
			});
		$('#dialog').dialog('open');
	    }
	adduser = function(textid, text, offset) {
		$("#utextid").attr("value",textid);
		$("#uremove").attr("value",0);
		$("#userform").css({ display: 'block',top: offset.top, left: offset.left } );
		}
		
	userchoice = function(v) {
		$("#validator").attr("value",v);
		$("#uremove").attr("value",0);		
		$("#useraddremove").submit();	
		}
	
	userremove = function(tid,uid) {	
		$("#utextid").attr("value",tid);
		$("#uremove").attr("value",uid);
		$("#useraddremove").submit();
		}
	nextstatus = function(tid) {
		//console.log("nextstatus",tid)	
	
		$.ajax({
			type: "POST",
			url: "statusChange.cgi",//CGI REF!!!
			data: {"project":project,"userid":userid,"username":username,"textid":tid}, 
			success: function(answer){
					$("#textStatus"+tid).html(answer.status);
					//console.log("changed!",answer);
					
				},
			error: function(XMLHttpRequest, textStatus, errorThrown){
				console.log("error",project,erasetreeid)}
			});
	    }	
    nl2br = function(str) {   
        return (str + '').replace(/([^>\\r\\n]?)(\\r\\n|\\n\\r|\\r|\\n)/g, '$1'+ '<br>' +'$2');
	    }

	startmate = function() {
		//$("#startmateform :input").prop('disabled', true);
		//checkMate();
		$("#parseStatus").css('background-image', 'url("images/ajax-loader.gif")');  
		$.ajax({
			type: "POST",
			url: "mate.cgi",//CGI REF!!!!
			data: {"project":project,"parserType":$( "#parserType" ).val(), "whoseTrees":$( "#whoseTrees" ).val(), "evaluationPercent":$( "#evaluationPercent" ).val(), "additionnalLexicon":$( "#additionnalLexicon" ).val(), "resultAnnotator":$( "#resultAnnotator" ).val()}, 
			success: function(answer){
					$("#parseStatus").html(answer);
					console.log("finished!",answer);
					//clearInterval(timer);
				},
			error: function(XMLHttpRequest, textStatus, errorThrown){
				console.log("mate error",project)
				
				}
			});
	
		timer = setInterval(checkMate, 5000);
		}
	
	checkMate = function() {
		$.ajax({
			url : "mate/parse.log",
			dataType: "text",
			cache: false,
			processData: false,
			success : function (data) {
				$("#parseStatus").html(nl2br(data));
				if (data.match("^Ready"))
					{
						console.log("Done");
						clearInterval(timer);
						$("#parseStatus").css('background-image', 'none'); 
						//$("#startmateform :input").prop('disabled', false);
					}
				}
			});
			

			
		}
	
	
	$(function () {
		$("#dialog").dialog({
			bgiframe: true,
			autoOpen: false,
			height: 350,
 			width:400,
			modal: true,
			buttons: {
				
				Cancel: function() {
					$(this).dialog('close');
				},
				"OK": function() {
					$(this).dialog('close');					
					$("#erase").submit();
				}
				}
			});
			
		$('#exochoice').change(function ()
			{
				$('#exochange').submit();
			});	
			
		

	})
	

	getEvaluation = function(project,uid) {
		$("#evalubutton"+uid).replaceWith("<img id='evalubutton"+uid+"' src='images/ajax-loader.gif'>");
		$.ajax({
			type: "GET",
			url: "getEvaluation.cgi", //CGI REF!!!!
			data: {"project":project,"uid":uid}, 
			success: function(answer){
					$("#evalubutton"+uid).replaceWith(answer);
					//console.log("got!"+answer);
			
				},
			error: function(XMLHttpRequest, textStatus, errorThrown){
				console.log("error",project)
				alert("error erasing"+XMLHttpRequest+ '\\n'+textStatus+ "\\n"+errorThrown);
				}
			});
		
	}
	
</script>
{% endblock %}
{% block body %}
<div id="center" class="center" style="width:100%">
				<div id="navigation" style="width:100%;margin:0px;border:0px;" class="arbortitle  ui-widget-header ui-helper-clearfix">
				<a href='.' style='position: fixed;left:1px;top:1px'><img src="{{ url_for ('static', filename='images/arboratorNano.png') }}" border="0"></a>
				<a href="{{ url_for('project.projectpage', project_name')}}" style='position: fixed;left:120px;top:5px;color:white;' title="project overview">{{img}} {{project_name}} Annotation Project</a>
				<div style='margin:5 auto;' id='sentinfo'>Project Overview</div>
					<form method="get" action="project.cgi"  id="searchform"  style='position: fixed;right:1px;top:1px'>
						<input type="text" id="searchtext" name="searchtext" value="{query}"/>
						<input type="hidden" id="project" name="project" value="{project}">
						<span title="search" onClick="$('#searchform').submit();" style="cursor:pointer;" class="ui-button-icon-primary ui-icon ui-icon-search"></span>
					</form>
                </div>
                <div class="ui-widget ui-widget-content ui-corner-all box"  style="text-align:-moz-center;">
                    You have been assigned the following texts of the <b>{{project_name}}</b> Project<br/>
                    Please select the text to annotate:<br/><br/>
                    <table class="whitable">
                    <tr><td>text name</td><td>number of sentences</td><td>number of tokens</td><td>trees modified by you</td><td>status</td></tr>
                    </table>

                    <div class="ui-widget ui-widget-content ui-corner-all box"  style="text-align:-moz-center;" id='projectbox'>
                        The <b>{project}</b> Project has {{nrt}} texts and {{nrs}} sentences. <br/>
                        <br/>
                        <table class='whitable'>
                        <thead><tr><th>text name</th><th>number of sentences</th><th>number of tokens</th><th>sentence length</th><th >annotators</th><th>validator</th><th title='non sollicitated trees by users not assigned to this text are listed here.'>other trees</th><th>exo</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th></tr></thead>
{% endblock %}

app/templates/projects/project.html
{% extends "base.html" %}
{% block title %}{{project}}{% endblock %}
{% block head_js %}
<script type="text/javascript">	
	project="{project}";
	userid="{userid}";
	username="{username}";
    $('html').click(function() {
		$("#exportdiv").css({ display: 'none' } );	
		$("#userform").css({ display: 'none' } );	
		$("#exoform").css({ display: 'none' } );	
		});

	edit = function(textid,opensentence) {
		$("#textid").attr("value", textid );
		$("#opensentence").attr("value", opensentence );
		$("#editorform").submit();
	    }
	removeSample = function(textid, text) {
		$("#eraseNumber").attr("value",textid);
		$("#question").html("Are you sure that you want to erase the text "+text+" from the database?")
		$('#dialog').dialog('open');
		}
	exportAnnos = function(textid, text, offset) {
		$("#exportNumber").attr("value",textid);
		$("#textname").attr("value",text);
		offset.left=offset.left-280;
		$("#exportdiv").offset(offset).css({ display: 'inline' } );
		}	
	exportGo = function(type) {
		$("#exportType").attr("value",type);
		console.log($("#export"))
		$("#export").submit();
		$("#dialog").html("<img src='images/loading.gif'>");
		$("#dialog").dialog({
			height: 230,
 			width:150,
			modal: true,
			title:"Please wait!!!<br>This can be long.",
			buttons: {}
			});
		$('#dialog').dialog('open');
	    }
	adduser = function(textid, text, offset) {
		$("#utextid").attr("value",textid);
		$("#uremove").attr("value",0);
		$("#userform").css({ display: 'block',top: offset.top, left: offset.left } );
		}
		
	userchoice = function(v) {
		$("#validator").attr("value",v);
		$("#uremove").attr("value",0);		
		$("#useraddremove").submit();	
		}
	
	userremove = function(tid,uid) {	
		$("#utextid").attr("value",tid);
		$("#uremove").attr("value",uid);
		$("#useraddremove").submit();
		}
	nextstatus = function(tid) {
		//console.log("nextstatus",tid)	
	
		$.ajax({
			type: "POST",
			url: "statusChange.cgi",//CGI REF!!!
			data: {"project":project,"userid":userid,"username":username,"textid":tid}, 
			success: function(answer){
					$("#textStatus"+tid).html(answer.status);
					//console.log("changed!",answer);
					
				},
			error: function(XMLHttpRequest, textStatus, errorThrown){
				console.log("error",project,erasetreeid)}
			});
	    }	
    nl2br = function(str) {   
        return (str + '').replace(/([^>\\r\\n]?)(\\r\\n|\\n\\r|\\r|\\n)/g, '$1'+ '<br>' +'$2');
	    }

	startmate = function() {
		//$("#startmateform :input").prop('disabled', true);
		//checkMate();
		$("#parseStatus").css('background-image', 'url("images/ajax-loader.gif")');  
		$.ajax({
			type: "POST",
			url: "mate.cgi",//CGI REF!!!!
			data: {"project":project,"parserType":$( "#parserType" ).val(), "whoseTrees":$( "#whoseTrees" ).val(), "evaluationPercent":$( "#evaluationPercent" ).val(), "additionnalLexicon":$( "#additionnalLexicon" ).val(), "resultAnnotator":$( "#resultAnnotator" ).val()}, 
			success: function(answer){
					$("#parseStatus").html(answer);
					console.log("finished!",answer);
					//clearInterval(timer);
				},
			error: function(XMLHttpRequest, textStatus, errorThrown){
				console.log("mate error",project)
				
				}
			});
	
		timer = setInterval(checkMate, 5000);
		}
	
	checkMate = function() {
		$.ajax({
			url : "mate/parse.log",
			dataType: "text",
			cache: false,
			processData: false,
			success : function (data) {
				$("#parseStatus").html(nl2br(data));
				if (data.match("^Ready"))
					{
						console.log("Done");
						clearInterval(timer);
						$("#parseStatus").css('background-image', 'none'); 
						//$("#startmateform :input").prop('disabled', false);
					}
				}
			});
			

			
		}
	
	
	$(function () {
		$("#dialog").dialog({
			bgiframe: true,
			autoOpen: false,
			height: 350,
 			width:400,
			modal: true,
			buttons: {
				
				Cancel: function() {
					$(this).dialog('close');
				},
				"OK": function() {
					$(this).dialog('close');					
					$("#erase").submit();
				}
				}
			});
			
		$('#exochoice').change(function ()
			{
				$('#exochange').submit();
			});	
			
		

	})
	

	getEvaluation = function(project,uid) {
		$("#evalubutton"+uid).replaceWith("<img id='evalubutton"+uid+"' src='images/ajax-loader.gif'>");
		$.ajax({
			type: "GET",
			url: "getEvaluation.cgi", //CGI REF!!!!
			data: {"project":project,"uid":uid}, 
			success: function(answer){
					$("#evalubutton"+uid).replaceWith(answer);
					//console.log("got!"+answer);
			
				},
			error: function(XMLHttpRequest, textStatus, errorThrown){
				console.log("error",project)
				alert("error erasing"+XMLHttpRequest+ '\\n'+textStatus+ "\\n"+errorThrown);
				}
			});
		
	}
	
</script>
{% endblock %}
{% block body %}
<div id="center" class="center" style="width:100%">
				<div id="navigation" style="width:100%;margin:0px;border:0px;" class="arbortitle  ui-widget-header ui-helper-clearfix">
				<a href='.' style='position: fixed;left:1px;top:1px'><img src="{{ url_for ('static', filename='images/arboratorNano.png') }}" border="0"></a>
				<a href="{{ url_for('project.projectpage', project_name')}}" style='position: fixed;left:120px;top:5px;color:white;' title="project overview">{{img}} {{project_name}} Annotation Project</a>
				<div style='margin:5 auto;' id='sentinfo'>Project Overview</div>
					<form method="get" action="project.cgi"  id="searchform"  style='position: fixed;right:1px;top:1px'>
						<input type="text" id="searchtext" name="searchtext" value="{query}"/>
						<input type="hidden" id="project" name="project" value="{project}">
						<span title="search" onClick="$('#searchform').submit();" style="cursor:pointer;" class="ui-button-icon-primary ui-icon ui-icon-search"></span>
					</form>
                </div>
                <div class="ui-widget ui-widget-content ui-corner-all box"  style="text-align:-moz-center;">
                    You have been assigned the following texts of the <b>{{project_name}}</b> Project<br/>
                    Please select the text to annotate:<br/><br/>
                    <table class="whitable">
                    <tr><td>text name</td><td>number of sentences</td><td>number of tokens</td><td>trees modified by you</td><td>status</td></tr>
                    </table>

                    <div class="ui-widget ui-widget-content ui-corner-all box"  style="text-align:-moz-center;" id='projectbox'>
                        The <b>{project}</b> Project has {{nrt}} texts and {{nrs}} sentences. <br/>
                        <br/>
                        <table class='whitable'>
                        <thead><tr><th>text name</th><th>number of sentences</th><th>number of tokens</th><th>sentence length</th><th >annotators</th><th>validator</th><th title='non sollicitated trees by users not assigned to this text are listed here.'>other trees</th><th>exo</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th></tr></thead>
{% endblock %}